/**
 * Extra EasyList-syntax rules for file-hoster popunders and download-page ads.
 * Ghostery EasyList is loaded at runtime; this covers the networks those pages
 * use most, including the first launch before lists are cached.
 */
export const EXTRA_FILTERS = `
! Popup / popunder networks (this engine ignores $popup, so these are host blocks)
||popads.net^
||popads.com^
||popadex.net^
||popcash.net^
||popmyads.com^
||popunder.net^
||propellerads.com^
||propellerclick.com^
||adsterra.com^
||adsterra.org^
||clickadu.com^
||clickadilla.com^
||exoclick.com^
||exosrv.com^
||exdynsrv.com^
||juicyads.com^
||juicyads.me^
||trafficjunky.com^
||trafficjunky.net^
||tsyndicate.com^
||hilltopads.com^
||hilltopads.net^
||trafficstars.com^
||onclckd.com^
||onclcktv.com^
||ad-maven.com^
||admaven.com^
||adcash.com^
||bidvertiser.com^
||plugrush.com^
||adcell.com^
||smartadserver.com^
||adnxs.com^
||adsrvr.org^
||openx.net^
||pubmatic.com^
||rubiconproject.com^
||criteo.com^
||criteo.net^
||outbrain.com^
||taboola.com^
||mgid.com^
||revcontent.com^
||doubleclick.net^
||googlesyndication.com^
||googleadservices.com^
||adservice.google.com^
||pagead2.googlesyndication.com^
||fundingchoicesmessages.google.com^
||ads.yahoo.com^
||advertising.com^
||adtechus.com^
||adform.net^
||indexww.com^
||casalemedia.com^
||contextweb.com^
||openxcdn.net^
||ad-delivery.net^
||adtrafficquality.google^
||zedo.com^
||infolinks.com^
||propeller-tracking.com^
||adexchangeprediction.com^
||adexchangegate.com^
||adexchanges.io^
||onclickalgo.com^
||onclickgenius.com^
||onclickmega.com^
||onclicksuper.com^
||onclickperformance.com^
||stripchat.com^
||chaturbate.com^
||livejasmin.com^

! Fake download / push-notification / overlay vendors
||pushalert.co^
||pushengage.com^
||onesignal.com^
||webpushs.com^
||push-notifications.online^
||adblock-tester.com^
||disable-adblock.com^
||blockadblock.com^

! Hide leftover empty slots when cosmetic lists are not loaded yet
##iframe[src*="ads."]
##iframe[id*="google_ads"]
##iframe[id*="ad_iframe"]
##.adsbygoogle
##[id^="div-gpt-ad"]
##[class*="ad-container"][class*="popup"]
`.trim()
